/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/light_saber.glb -t -r public 
Author: Mathis Proux (https://sketchfab.com/MaMaNo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/light-saber-b0a48d6e600f44b1949356231a4d8488
Title: Light Saber
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane_0: THREE.Mesh
    Plane_1: THREE.Mesh
    Plane_2: THREE.Mesh
    Plane_3: THREE.Mesh
  }
  materials: {
    metal: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/light_saber.glb') as unknown as GLTFResult
  
  // Ensure the blade part glows brilliantly
  React.useMemo(() => {
    // Material.001 and Material.002 frequently map to the blade/glow cores
    if (materials['Material.001']) {
      materials['Material.001'].emissiveIntensity = 4;
    }
    if (materials['Material.002']) {
      materials['Material.002'].emissiveIntensity = 4;
    }
  }, [materials]);

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.128}>
        <group scale={2.985}>
          <mesh geometry={nodes.Plane_0.geometry} material={materials.metal} />
          <mesh geometry={nodes.Plane_1.geometry} material={materials.Material} />
          <mesh geometry={nodes.Plane_2.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Plane_3.geometry} material={materials['Material.001']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/light_saber.glb')
